---

- name: "set facts"
  set_fact:
    default_docker_labels: "name={{ docker_container_name }}"
    default_docker_restart_policy: "unless-stopped"
    default_not_defined_label: "None"
    default_container_privileged: "no"
    default_docker_registry_images_pull: "no"
    default_docker_container_state: "started"
    default_docker_volume_driver: "local"
    default_docker_container_userid: "root"
    default_docker_command: ""
    default_docker_published_ports: []
    set_docker_labels: "{{ docker_labels | default('name={{ docker_container_name }}') }}"
  tags:
    - always

- name: ensure container is started with params {{ role_comment }}
  debug:
    msg:
      - "docker_container_name: {{ docker_container_name }}"
      - "docker_image: {{ docker_image }}"
      - "docker_image_tag: {{ docker_image_tag }}"
      - "docker_image_to_run: {{ docker_image }}{% if docker_image %}:{% endif %}{{ docker_image_tag }}"
      - "docker_published_ports: {{ docker_published_ports | default([]) }}"
      - "docker_restart_policy: {{ docker_restart_policy | default(default_docker_restart_policy) }}"
      - "default_docker_restart_policy: {{ default_docker_restart_policy }}"
      - "docker_links: {{ docker_links | default([]) }}"
      - "docker_volumes: {{ docker_volumes | default([]) }}"
      - "docker_volume_driver: {{ docker_volume_driver | default(default_docker_volume_driver) }}"
      - "docker_command: {{ docker_command | default(default_docker_command) }}"
      - "default_docker_command: {{ default_docker_command }}"
      - "docker_labels: {{ docker_labels | default('') }}"
      - "set_docker_labels: {{ set_docker_labels | default('') }}"
      - "docker_container_restart: {{ container_restart | default(false) }}"
      - "docker_container_userid: {{ docker_container_userid | default(default_docker_container_userid) }}"
      - "default_docker_container_userid: {{ default_docker_container_userid }}"
      - "docker_env: {{ docker_env }}"
      - "docker_registry_images_pull: {{ docker_registry_images_pull }}"
      - "docker_container_privileged: {{ docker_container_privileged | default(default_container_privileged) }}"
      - "default_container_privileged: {{ default_container_privileged }}"
      - "default_docker_container_state: {{ default_docker_container_state }}"
      - "docker_container_state: {{ docker_container_state | default(default_docker_container_state) }}"
      - "default_docker_volume_driver: {{ default_docker_volume_driver }}"
      - "docker_host: {{ docker_host }}"
  no_log: "{{ debug_hide }}"

- name: ensure container is started {{ role_comment | default('') }}
  docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image }}{% if docker_image %}:{% endif %}{{ docker_image_tag }}"
    state: "{{ docker_container_state | default(default_docker_container_state) }}"
    user: "{{ docker_container_userid | default(default_docker_container_userid) }}"
    published_ports: "{{ docker_published_ports | default(default_docker_published_ports) }}"
    restart_policy: "{{ docker_restart_policy | default(default_docker_restart_policy) }}"
    links: "{{ docker_links | default([]) }}"
    volumes: "{{ docker_volumes | default([]) }}"
    volume_driver: "{{ docker_volume_driver | default(default_docker_volume_driver) }}"
    pull: "{{ docker_registry_images_pull | default(default_docker_registry_images_pull) }}"
    env: "{{ docker_env }}"
    command: "{{ docker_command | default(default_docker_command) }}"
    labels: "{{ set_docker_labels | default('') }}"
    docker_host: "{{ docker_host | default('') }}"
    privileged: "{{ docker_container_privileged | default(default_container_privileged) }}"
    restart: "{{ docker_container_restart }}"
  become: true
  become_method: sudo
  when:
    - docker_container_restart | default(true)
    - docker_container_name | length > 0
    - docker_image | length > 0
    - docker_image_tag | length > 0
  tags:
    - always

- name: ensure container is re-started {{ role_comment | default('') }}
  docker_container:
    name: "{{ docker_container_name }}"
    state: "{{ docker_container_state | default('started') }}"
    restart: "{{ docker_container_restart | default(false) }}"
  become: true
  become_method: sudo
  when:
    - docker_container_name | length > 0
    - docker_container_restart is defined
  tags:
    - always
