---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: docker_container
      debug_hide: false
      vars:
        docker_container_name: "author"
        docker_image: "aemdesign/aem"
        docker_image_tag: "latest"
        docker_published_ports: [
          "0.0.0.0:{{ aem_port }}:8080/tcp",
          "0.0.0.0:{{ aem_debug_port }}:58242/tcp",
          "0.0.0.0:{{ aem_imageserver_port }}:57345/tcp"
        ]
        docker_volumes: [
          "author-repository:/aem/crx-quickstart/repository:z",
          "author-logs:/aem/crx-quickstart/logs:z",
          "author-backup:/aem/backup:z"
        ]
        docker_env:
          TZ: "{{ docker_timezone }}"
          AEM_JVM_OPTS: "{{ aem_jvm_opts }}"
          AEM_START_OPTS: "{{ aem_start_opts }}"
          AEM_RUNMODE: "{{ aem_runmode }}"
